# Nom de l'application
spring.application.name=reservationVoiture

# Local development settings
server.port=8086

# PostgreSQL local
spring.datasource.url=jdbc:postgresql://localhost:5432/reservation_voiture
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate (local)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# External reservations API (returns JSON list of reservations with hotel name)
external.api.reservations.url=http://localhost:8080/reservation/api/reservation/list
external.api.reservations.token=b01b5e66-a558-486f-ab95-a91b047a3ef2
#api/reservation/list
# JSP view resolver
spring.mvc.view.prefix=/WEB-INF/jsp/
spring.mvc.view.suffix=.jsp
